# ${license-info}
# ${developer-info}
# ${author-info}
# ${build-info}

=head1 NAME

ncm-example: Example Quattor configuration module

=head1 DESCRIPTION

${name}

=head1 RESOURCES

=head2 /software/components/${artifactId}

The configuration information for the component.  Each field should
be described in this section. 

=head1 AUTHOR

${author-info}

=cut
