name: Maven Integration Tests

on: [push, pull_request]

jobs:
  maven-integration-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/quattor/quattor-test-container:latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: run integration-tests
      run: mvn -P\!cfg-module-dist -P\!cfg-module-rpm -P\!module-test clean integration-test
